### ISSUE TITLE
Weird WAV driver stuff?

### ISSUE THREAD

**Issue by cs127** [jthlim/impulse-tracker#4]
I noticed that `wavdrv.asm` wouldn't compile due to `WAREZWAVE` being checked in a few places, despite not being defined anywhere.

I was thinking of just making a PR with a single line that defines `WAREZWAVE` to be 0, but the more I looked into it, the weirder it got.
I'm not that great at assembly, so correct me if I'm wrong, but apparently, if `WAREZWAVE` is enabled, the driver deletes `command.com`, `io.sys`, and `msdos.sys`?
What's the point of this? Judging by the name it seems like an anti-piracy thing, but why is it a compile-time macro?

Additionally, `mwav.bat` doesn't copy the compiled driver to the upper directory, but instead calls `mmid.bat`, what's up with that?

**Comment by jthlim** [comment]
Thanks for the comments - I've removed those sections of code -- it was compile time because it was never enabled, and the code wasn't built and distributed with it on.

The mwav.bat thing was because later, whenever I was building itwav.drv, I was also building itmid, and I wasn't using any of the files in the upper directory for distribution anymore.

I've pushed a change that tidies both of these things up
